### ISSUE TITLE
Cannot find prepare_graph_data.md

### ISSUE THREAD

**Issue by Chanrom** [microsoft/DeepGNN#31]
Hi,
Thanks for sharing the code! 
I am wondering where I can find the instruction to prepare graph data. I check GAT example, it says we can refer to [https://github.com/microsoft/DeepGNN/blob/main/docs/prepare_graph_data.md](https://github.com/microsoft/DeepGNN/blob/main/docs/prepare_graph_data.md) but seems this page is not available. 
Could you help with this?

**Comment by coledie** [comment]
Here is the proper link, https://github.com/microsoft/DeepGNN/blob/main/docs/advanced/data_spec.md
Thank you for documenting this, I will submit a PR fix.
